# Generated by Django 6.0.6 on 2026-06-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cpu_threshold',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='server',
            name='disk_threshold',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='server',
            name='last_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='ram_threshold',
            field=models.IntegerField(default=85),
        ),
        migrations.AddField(
            model_name='server',
            name='server_type',
            field=models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows'), ('other', 'Other')], default='linux', max_length=20),
        ),
    ]
