# Generated by Django 6.0.6 on 2026-06-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_server_cpu_threshold_server_disk_threshold_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarm',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='metric',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.RemoveField(
            model_name='server',
            name='ssh_password',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ssh_port',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ssh_user',
        ),
        migrations.AddField(
            model_name='server',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
